---
driver:
  name: vagrant

#add proxy to provisioner
provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ---specify Ubuntu version or change all files for other os

suites:
  - name: default
    run_list:
      - recipe[jupyter::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
