---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ---specify amazon based linux machine

suites:
  - name: default
    run_list:
      - recipe[jupyter::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
